create table
  public.global_inventory (
    num_green_ml integer not null default 0,
    gold integer generated by default 0,
    num_red_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint global_inventory_pkey primary key (gold)
  ) tablespace pg_default;

create table
  public.potion_table (
    id integer generated by default as identity,
    sku text not null,
    price integer not null default 0,
    quantity integer not null default 0,
    potion_name text null,
    red integer not null default 0,
    green integer not null default 0,
    dark integer not null default 0,
    blue integer not null default 0,
    constraint potion_table_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts (
    id integer generated by default as identity,
    class text null,
    name text null,
    level integer null default 0,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.carts_items (
    id integer generated by default as identity,
    customer_id integer null,
    quantity integer null,
    item_id integer null,
    constraint carts_items_pkey primary key (id),
    constraint public_carts_items_customer_id_fkey foreign key (customer_id) references carts (id),
    constraint public_carts_items_item_id_fkey foreign key (item_id) references potion_table (id)
  ) tablespace pg_default;